### ISSUE TITLE
Error generating thumbnails in Dolphin

### ISSUE THREAD

**Issue by paul** [unlimitedbacon/stl-thumb-kde#5]
When I open Dolphin in a folder full of .stl files, a few render thumbnails, but most do not.

![image](https://github.com/unlimitedbacon/stl-thumb-kde/assets/184/dcab5fc1-5a6a-4e4a-a6fb-8f9f0335129d)

If I watch the log when I open the folder, it gets filled with error messages like this:

```
Jun 01 10:47:43 ava.home plasmashell[2788635]: thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/rando/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/event_loop.rs:106:13
Jun 01 10:47:43 ava.home plasmashell[2788635]: thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/rando/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/event_loop.rs:106:13
Jun 01 10:47:43 ava.home kioslave5[2788635]: com.stl-thumb-kde: STL-THUMB :: lib returned error
Jun 01 10:47:43 ava.home plasmashell[2788635]: thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/rando/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/event_loop.rs:106:13
Jun 01 10:47:43 ava.home plasmashell[2788635]: thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/rando/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/event_loop.rs:106:13
Jun 01 10:47:43 ava.home kioslave5[2788635]: com.stl-thumb-kde: STL-THUMB :: lib returned error
Jun 01 10:47:44 ava.home plasmashell[2788635]: thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/rando/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/event_loop.rs:106:13
Jun 01 10:47:44 ava.home plasmashell[2788635]: thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/rando/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/event_loop.rs:106:13
Jun 01 10:47:44 ava.home kioslave5[2788635]: com.stl-thumb-kde: STL-THUMB :: lib returned error
```

This is using `plasmashell 5.27.5` on Fedora 38.

**Comment by twelho** [comment]
Same issue, with `stl-thumb 0.5.0` and `stl-thumb-kde 0.4.0` built from source on Fedora 38:

```
thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.3/src/event_loop.rs:106:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Creating EventLoop multiple times is not supported.', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.3/src/event_loop.rs:106:13
com.stl-thumb-kde: STL-THUMB :: lib returned error
```

Sometimes when re-entering a directory I get a single additional thumbnail before `stl-thumb` panics.

**Comment by alextrical** [comment]
I have noticed similar issues too, but not had chance to look into the cause of the issue. Its something I will be investigating over the holiday

**Comment by alextrical** [comment]
So from what I can tell some of those errors are coming from stl-thumb, but also don't look to be terminal, but could be causing some of the issues of "Running multiple times" as parts are "still attached"
![image](https://github.com/unlimitedbacon/stl-thumb-kde/assets/35117191/f756befb-79e9-4dbf-9a2a-eca4ea9d3b68)

**Comment by twelho** [comment]
From what I remember looking into this, the core issue is the following: Dolphin will load `stl-thumb-kde` into memory once on startup and then [call `render_to_buffer`](https://github.com/unlimitedbacon/stl-thumb-kde/blob/79abfa5210386a3d9997ac8c9131b81aba4a94d0/stlcreator.cpp#L33) for every file. `render_to_buffer` calls [`render_to_image` in a separate thread](https://github.com/unlimitedbacon/stl-thumb/blob/754805e8f0ef577f05e53211abf2681db5642b69/src/lib.rs#L482), which then calls [`create_headless_display`](https://github.com/unlimitedbacon/stl-thumb/blob/754805e8f0ef577f05e53211abf2681db5642b69/src/lib.rs#L97). However, there was a global [`static OnceCell` in place](https://github.com/rust-windowing/winit/issues/2431#issuecomment-1464974177), which prevented creating multiple contexts, even across threads, without unloading and reloading the application, resulting in https://github.com/unlimitedbacon/stl-thumb-kde/issues/5#issuecomment-1656252503. However, it seems like stuff has changed a lot over in `glutin/glium` land. The [currently used version](https://docs.rs/glium/0.32.1/glium/) in `stl-thumb` still has the [check in place](https://docs.rs/winit/0.27.5/src/winit/event_loop.rs.html#103). Similarly, for the latest `glium`, one needs to [use `winit` directly](https://docs.rs/glium/0.33.0/glium/index.html) for creating the event loop, and the check is still there, however, it is a [bit more graceful](https://github.com/rust-windowing/winit/blob/master/src/event_loop.rs#L121-L123) now.

Ultimately, the correct solution would be to initialize the event loop and graphics context exactly once as the application is initialized, and not for every thumbnail rendering invocation. As a bonus, this should also be faster, since rendering a single thumbnail will not require a full context initialization.

**Comment by Grntrenchman** [comment]
It looks like I'm getting the same errors from dolphin, and symptoms. I can mouse over STL in a folder full of them, and maybe 1-2 will get thumb every couple mins. Once generated, they cache and load fine.

At open with RUST_BACKTRACE=full (already in a folder full of STL) I get:
```
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::checkRequested(QString)
qt.core.qobject.connect: QObject::connect: No such signal Solid::Backends::Fstab::FstabStorageAccess::checkDone(Solid::ErrorType, QVariant, QString)
thread '<unnamed>' panicked at src/lib.rs:482:72:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
stack backtrace:
   0:     0x76fda8675bb6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h51d543060edb7cff
   1:     0x76fda869bf60 - core::fmt::write::hae0051a5742dd8d1
   2:     0x76fda867361d - std::io::Write::write_fmt::h8f3c34b42f081303
   3:     0x76fda8675994 - std::sys_common::backtrace::print::h0920760b58223b7f
   4:     0x76fda86770b7 - std::panicking::default_hook::{{closure}}::h69c45358023635c5
   5:     0x76fda8676e19 - std::panicking::default_hook::hc0bca377b3bff2c0
   6:     0x76fda8677548 - std::panicking::rust_panic_with_hook::h7ccec12e18a1672c
   7:     0x76fda8677422 - std::panicking::begin_panic_handler::{{closure}}::hae011cee41432601
   8:     0x76fda86760b6 - std::sys_common::backtrace::__rust_end_short_backtrace::hfcbcce25bb2091e5
   9:     0x76fda8677174 - rust_begin_unwind
  10:     0x76fda844fe25 - core::panicking::panic_fmt::h6e6ea790b1ee0887
  11:     0x76fda8450373 - core::result::unwrap_failed::h27f612897e8aaec0
  12:     0x76fda84964c8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ffc96eb3774fe3a
  13:     0x76fda849da7d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h06c39f91e73cae47
  14:     0x76fda8679825 - std::sys::pal::unix::thread::Thread::new::thread_start::hb315287cd809ac3d
  15:     0x76fdcfc7dba8 - start_thread
  16:     0x76fdcfd01b8c - __clone3
  17:                0x0 - <unknown>
thread '<unnamed>' panicked at src/lib.rs:482:72:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
stack backtrace:
   0:     0x76fda8675bb6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h51d543060edb7cff
   1:     0x76fda869bf60 - core::fmt::write::hae0051a5742dd8d1
   2:     0x76fda867361d - std::io::Write::write_fmt::h8f3c34b42f081303
   3:     0x76fda8675994 - std::sys_common::backtrace::print::h0920760b58223b7f
   4:     0x76fda86770b7 - std::panicking::default_hook::{{closure}}::h69c45358023635c5
   5:     0x76fda8676e19 - std::panicking::default_hook::hc0bca377b3bff2c0
   6:     0x76fda8677548 - std::panicking::rust_panic_with_hook::h7ccec12e18a1672c
   7:     0x76fda8677422 - std::panicking::begin_panic_handler::{{closure}}::hae011cee41432601
   8:     0x76fda86760b6 - std::sys_common::backtrace::__rust_end_short_backtrace::hfcbcce25bb2091e5
   9:     0x76fda8677174 - rust_begin_unwind
  10:     0x76fda844fe25 - core::panicking::panic_fmt::h6e6ea790b1ee0887
  11:     0x76fda8450373 - core::result::unwrap_failed::h27f612897e8aaec0
  12:     0x76fda84964c8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ffc96eb3774fe3a
  13:     0x76fda849da7d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h06c39f91e73cae47
  14:     0x76fda8679825 - std::sys::pal::unix::thread::Thread::new::thread_start::hb315287cd809ac3d
  15:     0x76fdcfc7dba8 - start_thread
  16:     0x76fdcfd01b8c - __clone3
  17:                0x0 - <unknown>
warning: queue 0x76fd64002d60 destroyed while proxies still attached:
  zwp_text_input_manager_v3#13 still attached
  wl_output#12 still attached
  xdg_activation_v1#11 still attached
  wl_subcompositor#10 still attached
  zwp_relative_pointer_manager_v1#9 still attached
  zwp_pointer_constraints_v1#8 still attached
  wl_seat#7 still attached
  wl_shm#6 still attached
  zxdg_decoration_manager_v1#5 still attached
  wl_compositor#4 still attached
  wl_registry#2 still attached
```
followed by a bazillion
```
thread '<unnamed>' panicked at /home/trencher/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.3/src/event_loop.rs:106:13:
Creating EventLoop multiple times is not supported.
stack backtrace:
   0:     0x76fda8675bb6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h51d543060edb7cff
   1:     0x76fda869bf60 - core::fmt::write::hae0051a5742dd8d1
   2:     0x76fda867361d - std::io::Write::write_fmt::h8f3c34b42f081303
   3:     0x76fda8675994 - std::sys_common::backtrace::print::h0920760b58223b7f
   4:     0x76fda86770b7 - std::panicking::default_hook::{{closure}}::h69c45358023635c5
   5:     0x76fda8676e19 - std::panicking::default_hook::hc0bca377b3bff2c0
   6:     0x76fda8677548 - std::panicking::rust_panic_with_hook::h7ccec12e18a1672c
   7:     0x76fda86773e9 - std::panicking::begin_panic_handler::{{closure}}::hae011cee41432601
   8:     0x76fda86760b6 - std::sys_common::backtrace::__rust_end_short_backtrace::hfcbcce25bb2091e5
   9:     0x76fda8677174 - rust_begin_unwind
  10:     0x76fda844fe25 - core::panicking::panic_fmt::h6e6ea790b1ee0887
  11:     0x76fda84b0de1 - std::panicking::try::h8d1c73cb6860d4e4
  12:     0x76fda84dd444 - stl_thumb::render_to_image::he0b4649c060bed05
  13:     0x76fda849640c - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ffc96eb3774fe3a
  14:     0x76fda849da7d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h06c39f91e73cae47
  15:     0x76fda8679825 - std::sys::pal::unix::thread::Thread::new::thread_start::hb315287cd809ac3d
  16:     0x76fdcfc7dba8 - start_thread
  17:     0x76fdcfd01b8c - __clone3
  18:                0x0 - <unknown>
```
I'm running Nobara (Fedora) 41, KDE 6.3.3, stl-thumb 0.5.0-1
```
··• dnf list installed stl-thumb*
Updating and loading repositories:
Repositories loaded.
Installed packages
stl-thumb.x86_64     0.5.0-1 <unknown>
stl-thumb-kde.x86_64 0.5.0-1 <unknown>
··• uname -a
Linux COOLER 6.13.7-200.nobara.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 13 19:39:30 UTC 2025 x86_64 GNU/Linux
```

Let me know if there's anything I can do on my end or include to help

**Comment by mithkr** [comment]
I observe the same issue on latest openSUSE Tumbleweed, KDE 6.14.0 and stl-thumb build from latest git trunk.

**Comment by Jinra** [comment]
Same behavior on CachyOS 6.15.4

![Image](https://github.com/user-attachments/assets/5b822446-7185-4267-8e9b-582c3c8be342)

**Comment by doggocough** [comment]
A bit of a workaround, but at least on Arch, when I close and reopen Dolphin, it renders one more STL. You just have to keep closing and opening until all the STLs render.

**Comment by MathisP75** [comment]
For anyone who wants this feature, `f3d` provides thumbnails for STLs and many other 3D formats.
